language: python
python:
- '3.3'

branches:
  only: 
  - master

script: echo "sample"

before_script:
- bin/gitLogin

after_success:
- bin/sendSuccessful

notifications:
  email: false

env:
  global:
  - GH_REPO="einaralex/TravisonBravis"
  - GH_NAME="einaralex"
  - GH_EMAIL="einaralex@gmail.com"
  - DEVELOPMENT="master"
  - SUCCESSFUL="travisOK"
  - secure: GHC2n15UEext9i+OOySkZj5FQFQHCETCwIhIrsZY3ahoT9l9EM3iSFzNI+X0zDOAYp8+pDSxno8TwRZs3rxhHwdLihRAxU4B9FqCAOjUd7oVTr+G11bpnu/roZ6dLr01LfjWJZyvnGGAxTjb8jzHlpPi/EtDL4D+sDFnyRc+tMU=
